name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Release version (e.g. 2025.1.0)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Retrieve credentials
        run: |
          mkdir -p ~/.m2
          curl -f -u "${{secrets.MAVEN_USERNAME}}:${{secrets.MAVEN_TOKEN}}" https://repo.jenkins-ci.org/setup/settings.xml -o ~/.m2/settings.xml
      - name: Configure Git for tagging
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Release with Maven
        run: ./mvnw -B release:prepare release:perform -DreleaseVersion="${{inputs.version}}"
